# Generated by Django 5.0.1 on 2024-03-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_price_record_total_price_record_inital_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
