# Generated by Django 5.0.1 on 2024-02-21 18:04

import chicken.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('moreInfo', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('dates', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to=chicken.models.upload_location1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentsInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('moreInfo', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('Image', models.ImageField(upload_to=chicken.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedsInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('moreInfo', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('Image', models.ImageField(upload_to=chicken.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('moreInfo', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('Image', models.ImageField(upload_to=chicken.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
